#ifdef TARGET_I386
#define TARGET_ARCH "i386"
#define TARGET_I386 1
#define TARGET_TYPE TARGET_TYPE_I386
#define CONFIG_QEMU_LDST_OPTIMIZATION
#elif defined(TARGET_ALPHA)
#define TARGET_ARCH "alpha"
#define TARGET_ALPHA 1
#define TARGET_LONG_BITS 64
#define TARGET_TYPE TARGET_TYPE_ALPHA
#define TARGET_PHYS_ADDR_SPACE_BITS 44
#define CONFIG_QEMU_LDST_OPTIMIZATION
#endif
